
-- Clear existing test data
DELETE FROM public.chat_messages;
DELETE FROM public.chat_sessions;
DELETE FROM public.questionnaire_responses;

-- Add new fields
ALTER TABLE public.questionnaire_responses
  ADD COLUMN IF NOT EXISTS date_of_birth date,
  ADD COLUMN IF NOT EXISTS leaders_by_year jsonb,
  ADD COLUMN IF NOT EXISTS captains_by_year jsonb,
  ADD COLUMN IF NOT EXISTS prefects_elected_or_appointed text,
  ADD COLUMN IF NOT EXISTS prefect_change_year text,
  ADD COLUMN IF NOT EXISTS notable_old_cambrian text,
  ADD COLUMN IF NOT EXISTS memorable_event text;

-- Drop fields no longer collected
ALTER TABLE public.questionnaire_responses
  DROP COLUMN IF EXISTS email,
  DROP COLUMN IF EXISTS phone,
  DROP COLUMN IF EXISTS current_location,
  DROP COLUMN IF EXISTS current_profession,
  DROP COLUMN IF EXISTS admission_number,
  DROP COLUMN IF EXISTS dormitory_name,
  DROP COLUMN IF EXISTS subjects_taken,
  DROP COLUMN IF EXISTS sports_participated,
  DROP COLUMN IF EXISTS clubs_societies,
  DROP COLUMN IF EXISTS was_prefect,
  DROP COLUMN IF EXISTS prefect_position,
  DROP COLUMN IF EXISTS was_sports_captain,
  DROP COLUMN IF EXISTS sports_captain_details,
  DROP COLUMN IF EXISTS was_club_leader,
  DROP COLUMN IF EXISTS club_leader_details,
  DROP COLUMN IF EXISTS headmaster_name,
  DROP COLUMN IF EXISTS deputy_headmaster_name,
  DROP COLUMN IF EXISTS housemaster_name,
  DROP COLUMN IF EXISTS class_teacher_names,
  DROP COLUMN IF EXISTS school_captain_name,
  DROP COLUMN IF EXISTS house_captain_name,
  DROP COLUMN IF EXISTS prefect_names_during_time,
  DROP COLUMN IF EXISTS uniform_memories,
  DROP COLUMN IF EXISTS daily_routine_memories,
  DROP COLUMN IF EXISTS timetable_description,
  DROP COLUMN IF EXISTS dining_memories,
  DROP COLUMN IF EXISTS favorite_meals,
  DROP COLUMN IF EXISTS canteen_memories,
  DROP COLUMN IF EXISTS dormitory_memories,
  DROP COLUMN IF EXISTS swimming_pool_memories,
  DROP COLUMN IF EXISTS weekend_activities,
  DROP COLUMN IF EXISTS punishments_memories,
  DROP COLUMN IF EXISTS visiting_days_memories,
  DROP COLUMN IF EXISTS opening_closing_day,
  DROP COLUMN IF EXISTS chapel_memories,
  DROP COLUMN IF EXISTS entertainment_memories,
  DROP COLUMN IF EXISTS games_and_hobbies,
  DROP COLUMN IF EXISTS house_colours_description,
  DROP COLUMN IF EXISTS inter_house_competitions,
  DROP COLUMN IF EXISTS favorite_teachers,
  DROP COLUMN IF EXISTS memorable_events,
  DROP COLUMN IF EXISTS funny_stories,
  DROP COLUMN IF EXISTS traditions_remembered,
  DROP COLUMN IF EXISTS rivalry_memories,
  DROP COLUMN IF EXISTS cultural_events,
  DROP COLUMN IF EXISTS religious_life,
  DROP COLUMN IF EXISTS significant_changes,
  DROP COLUMN IF EXISTS academic_achievements,
  DROP COLUMN IF EXISTS sports_achievements,
  DROP COLUMN IF EXISTS career_achievements,
  DROP COLUMN IF EXISTS advice_to_current,
  DROP COLUMN IF EXISTS notability,
  DROP COLUMN IF EXISTS signature_contribution,
  DROP COLUMN IF EXISTS school_connection,
  DROP COLUMN IF EXISTS legacy_note,
  DROP COLUMN IF EXISTS has_photos_to_share,
  DROP COLUMN IF EXISTS willing_to_be_interviewed,
  DROP COLUMN IF EXISTS additional_comments;
